- name: datatypes
  hosts: local
  connection: local
  vars:
    course: devops with aws #string
    duration: 10  #number
    topics: #list
    - linux
    - shell
    - ansible
    - terraform
    live: true #boolean
    tools: #map
      ci: jenkins
      cloud: aws
      containerization: docker
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "learning {{course}} in {{duration}}hrs which includes the topics are {{topics}} and the tools are {{tools}}. Is it live: {{live}}"