- name: shell vs command
  hosts: web
  # connection: local
  become: yes
  tasks:
  - name: executing shell module
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: executing command module
    ansible.builtin.command: ls -ltr 

  # - name: storing command module output
  #   ansible